# Generated by Django 2.0.1 on 2018-02-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CreateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='LastModified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
